# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-03 01:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('sex', models.BooleanField(default=True)),
                ('address', models.CharField(max_length=50)),
                ('door_number', models.CharField(max_length=20)),
                ('user_id', models.IntegerField()),
            ],
            options={
                'db_table': 'customeraddress',
            },
        ),
    ]
