# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-23 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_money', models.FloatField()),
                ('fake_money', models.FloatField()),
                ('customer_id', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'user_cards',
            },
        ),
        migrations.CreateModel(
            name='Customer_card_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.IntegerField()),
                ('real_money', models.FloatField()),
                ('fake_money', models.FloatField()),
                ('loggable_type', models.CharField(max_length=20, null=True)),
                ('loggable_id', models.IntegerField()),
                ('user_card_id', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'user_card_logs',
            },
        ),
    ]
