# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-23 17:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_card_customer_card_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer_card_charge_settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min', models.FloatField()),
                ('money_give', models.FloatField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'user_card_charge_settings',
            },
        ),
    ]
