# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-23 21:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_coupon'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='coupon',
            table='coupons',
        ),
    ]
