# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-16 08:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aliyun_msg', '0002_phonecaptcha_is_sent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phonecaptcha',
            old_name='update_date',
            new_name='create_date',
        ),
    ]
