# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-18 11:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('couriers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courier',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='courier',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
