# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-16 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couriers', '0002_auto_20171116_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='city_id',
            field=models.IntegerField(default=None),
        ),
    ]
