# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-19 02:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('couriers', '0002_auto_20171118_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courier',
            name='city_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='courier',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2017, 11, 19, 2, 52, 50, 567000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='courier',
            name='health_url',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='courier',
            name='idcard_url',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='courier',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='courier',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='courier',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='courier',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='courier',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='courier',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='courier',
            name='updated_at',
            field=models.DateField(default=datetime.datetime(2017, 11, 19, 2, 52, 50, 567000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='courier',
            name='user_back_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='courier',
            name='workplace',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
