# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-19 02:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('couriers', '0003_auto_20171119_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courier',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2017, 11, 19, 2, 56, 54, 694000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='courier',
            name='updated_at',
            field=models.DateField(default=datetime.datetime(2017, 11, 19, 2, 56, 54, 694000, tzinfo=utc)),
        ),
    ]
