# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-16 11:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('couriers', '0003_courier_city_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='courier',
            table=None,
        ),
    ]
