# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-19 03:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('couriers', '0004_auto_20171119_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courier',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 19, 3, 0, 24, 421000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='courier',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 19, 3, 0, 24, 421000, tzinfo=utc)),
        ),
    ]
