# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-19 06:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('couriers', '0005_auto_20171119_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('sex', models.BooleanField(default=True)),
                ('address', models.CharField(max_length=50)),
                ('door_number', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'customeraddress',
            },
        ),
        migrations.AlterField(
            model_name='courier',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 19, 6, 31, 7, 778000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='courier',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 19, 6, 31, 7, 778000, tzinfo=utc)),
        ),
    ]
