# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-19 07:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('couriers', '0006_auto_20171119_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraddress',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='courier',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 19, 7, 3, 27, 145000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='courier',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 19, 7, 3, 27, 145000, tzinfo=utc)),
        ),
    ]
