# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-10 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cleaning_status',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='courier_status',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='voucher_status',
            field=models.IntegerField(null=True),
        ),
    ]
