# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-15 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20171215_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='target_station',
            field=models.IntegerField(null=True),
        ),
    ]
