# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-15 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20171215_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
