# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-16 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20171216_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='courier_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='courier_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
