# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-03 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price1', models.FloatField()),
                ('price2', models.FloatField()),
                ('price3', models.FloatField()),
                ('price4', models.FloatField()),
                ('price5', models.FloatField()),
                ('price6', models.FloatField()),
                ('product_id', models.BigIntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'prices',
            },
        ),
    ]
